const SHORT_MOVIE_DURATION = 40;

const DESKTOP_CARDS_QUANTITY = 12;
const DESKTOP_MORE_QUANTITY = 3;

const TABLET_CARDS_QUANTITY = 8;
const TABLET_MORE_QUANTITY = 2;

const MOBILE_CARDS_QUANTITY = 5;
const MOBILE_MORE_QUANTITY = 2;

export {
    SHORT_MOVIE_DURATION,
    DESKTOP_CARDS_QUANTITY,
    DESKTOP_MORE_QUANTITY,
    TABLET_CARDS_QUANTITY,
    TABLET_MORE_QUANTITY,
    MOBILE_CARDS_QUANTITY,
    MOBILE_MORE_QUANTITY
};
