const SHORT_MOVIE_DURATION = 40;

const DEKTOP_WINDOW_WIDTH = 1024;
const TABLET_WINDOW_WIDTH = 1007;
const MOBILE_WINDOW_WIDTH = 635;

const DESKTOP_CARDS_QUANTITY = 12;
const DESKTOP_MORE_QUANTITY = 3;

const TABLET_CARDS_QUANTITY = 8;
const TABLET_MORE_QUANTITY = 2;

const MOBILE_CARDS_QUANTITY = 5;
const MOBILE_MORE_QUANTITY = 2;

const DELAY_TIME = 1200;



export {
    SHORT_MOVIE_DURATION,
    DEKTOP_WINDOW_WIDTH,
    TABLET_WINDOW_WIDTH,
    MOBILE_WINDOW_WIDTH,
    DESKTOP_CARDS_QUANTITY,
    DESKTOP_MORE_QUANTITY,
    TABLET_CARDS_QUANTITY,
    TABLET_MORE_QUANTITY,
    MOBILE_CARDS_QUANTITY,
    MOBILE_MORE_QUANTITY,
    DELAY_TIME
};
